### ISSUE TITLE
 Traceback most recent call last

### ISSUE THREAD

**Issue by G4EA5** [endim8/batch-colourise-deepai#4]
edit:

fixed

**Comment by hb0nd** [comment]
Updated instructions with c306621e1ce438ab8a5ac749ec4e6d233af5a5ca 
also added some QoL features like putting the API key into a separate TXT file 7063761685c56ba3927a1a050c4a980fa2f5c9dd, improved file input sanitisation & now it auto-opens the output folder once it's processed 0de54fde297d5de81cab4daac9311e177a8826b2 :)

**Comment by hb0nd** [comment]
Also, thank you for opening the first issue I've ever had on one of my repos ever :D it's cool to know I'm not just coding into the void haha

**Comment by G4EA5** [comment]
Hi,
I am pleased to open the first issue although the issue was likely my misunderstanding of python. In the end after getting all the libraries installed correctly your code worked very well. :) Thanks
